-- =============================================================================
-- Genie / Reframe — Interview 와 Dashboard 테이블 완전 분리 스키마
-- =============================================================================
-- 설계 원칙
--   * Interview 화면(/interview)         → int_interviews 테이블만 사용 (단독)
--   * Dashboard 화면(/dashboard)         → participant + 검사 테이블들 (단독)
--   * 두 영역이 "공통"으로 쓰는 것은 딱 둘:
--       1) 인증        : auth.users  +  public.counselors
--       2) 서명 저장소 : storage 'signatures' 버킷
--   * 그 외에는 서로 참조하지 않으므로 각자 독립적으로 저장/조회/삭제됩니다.
--
-- 사용법: Supabase 대시보드 → SQL Editor 에 전체를 붙여넣고 실행.
--         여러 번 실행해도 안전(idempotent)합니다.
-- =============================================================================

create extension if not exists "pgcrypto";


-- =============================================================================
-- [공통 1] 인증 — counselors (auth.users 와 1:1)
-- =============================================================================
create table if not exists public.counselors (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null unique references auth.users (id) on delete cascade,
    name text not null,
    email text not null,
    region text not null,
    photo_url text
);

-- 로그인 시 본인 counselor 행을 조회/생성하므로, 본인 행만 접근 허용
alter table public.counselors enable row level security;

drop policy if exists "counselors_select_self" on public.counselors;
create policy "counselors_select_self" on public.counselors
  for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists "counselors_insert_self" on public.counselors;
create policy "counselors_insert_self" on public.counselors
  for insert to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "counselors_update_self" on public.counselors;
create policy "counselors_update_self" on public.counselors
  for update to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);


-- =============================================================================
-- [공통 2] 서명 저장소 — storage 'signatures' 버킷
--   participant.signatureurl / int_interviews.signatureurl 둘 다 이 버킷을 가리킴
-- =============================================================================
insert into storage.buckets (id, name, public)
values ('signatures', 'signatures', true)
on conflict (id) do nothing;

drop policy if exists "signatures_public_read" on storage.objects;
create policy "signatures_public_read"
  on storage.objects for select to public
  using (bucket_id = 'signatures');

drop policy if exists "signatures_authenticated_insert" on storage.objects;
create policy "signatures_authenticated_insert"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'signatures');

drop policy if exists "signatures_authenticated_update" on storage.objects;
create policy "signatures_authenticated_update"
  on storage.objects for update to authenticated
  using (bucket_id = 'signatures')
  with check (bucket_id = 'signatures');


-- =============================================================================
-- [DASHBOARD] 코칭 대상자 — participant (단독)
-- =============================================================================
create table if not exists public.participant (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    birth_date text not null,
    stress text not null,
    religion text not null,
    signatureurl text not null,
    counselors uuid not null references auth.users (id) on delete cascade,
    created_at timestamptz not null default now()
);

-- 실수로 컬럼이 삭제/변경된 경우를 대비한 보정
alter table public.participant add column if not exists name text;
alter table public.participant add column if not exists birth_date text;
alter table public.participant add column if not exists stress text;
alter table public.participant add column if not exists religion text;
alter table public.participant add column if not exists signatureurl text;
alter table public.participant add column if not exists counselors uuid;
alter table public.participant add column if not exists created_at timestamptz not null default now();

create index if not exists idx_participant_counselors on public.participant (counselors);

alter table public.participant enable row level security;

drop policy if exists "participant_counselor_all" on public.participant;
create policy "participant_counselor_all" on public.participant
  for all to authenticated
  using (auth.uid() = counselors)
  with check (auth.uid() = counselors);


-- =============================================================================
-- [DASHBOARD] 검사 테이블들 — participant 에만 종속 (참가자 삭제 시 함께 삭제)
-- =============================================================================
create table if not exists public.core_emotion_tests (
    id bigint generated by default as identity primary key,
    participant_id uuid not null references public.participant (id) on delete cascade,
    answers jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.personality_tests (
    id bigint generated by default as identity primary key,
    participant_id uuid not null references public.participant (id) on delete cascade,
    answers jsonb not null default '{}'::jsonb
);

create table if not exists public.personality_tests2 (
    id bigint generated by default as identity primary key,
    participant_id uuid not null references public.participant (id) on delete cascade,
    answers jsonb not null default '{}'::jsonb
);

create table if not exists public.attachment_tests (
    id bigint generated by default as identity primary key,
    participant_id uuid not null references public.participant (id) on delete cascade,
    answers jsonb not null default '{}'::jsonb
);

create table if not exists public.lifegraphs (
    id bigint generated by default as identity primary key,
    participant_id uuid not null references public.participant (id) on delete cascade,
    image_url text not null
);

create table if not exists public.sixtypes (
    id bigint generated by default as identity primary key,
    participant_id uuid not null references public.participant (id) on delete cascade,
    image_url text not null
);

create table if not exists public.fourtypes (
    id bigint generated by default as identity primary key,
    participant_id uuid not null references public.participant (id) on delete cascade,
    image_url text not null
);

-- 검사 테이블 RLS: 해당 participant 를 소유한 상담사만 접근
do $$
declare
    t text;
begin
    foreach t in array array[
        'core_emotion_tests','personality_tests','personality_tests2',
        'attachment_tests','lifegraphs','sixtypes','fourtypes'
    ] loop
        execute format('alter table public.%I enable row level security;', t);
        execute format('drop policy if exists %I on public.%I;', t || '_by_owner', t);
        execute format($f$
            create policy %I on public.%I
              for all to authenticated
              using (exists (
                  select 1 from public.participant p
                  where p.id = %I.participant_id and p.counselors = auth.uid()
              ))
              with check (exists (
                  select 1 from public.participant p
                  where p.id = %I.participant_id and p.counselors = auth.uid()
              ));
        $f$, t || '_by_owner', t, t, t);
    end loop;
end $$;

-- 이미지 검사용 스토리지 버킷 (dashboard 전용)
insert into storage.buckets (id, name, public)
values
    ('lifegraph', 'lifegraph', true),
    ('sixtypes', 'sixtypes', true),
    ('fourtypes', 'fourtypes', true)
on conflict (id) do nothing;

do $$
declare
    b text;
begin
    foreach b in array array['lifegraph','sixtypes','fourtypes'] loop
        execute format('drop policy if exists %I on storage.objects;', b || '_public_read');
        execute format($f$
            create policy %I on storage.objects for select to public
            using (bucket_id = %L);
        $f$, b || '_public_read', b);

        execute format('drop policy if exists %I on storage.objects;', b || '_auth_insert');
        execute format($f$
            create policy %I on storage.objects for insert to authenticated
            with check (bucket_id = %L);
        $f$, b || '_auth_insert', b);
    end loop;
end $$;


-- =============================================================================
-- [INTERVIEW] 지니 인터뷰 — int_interviews (단독)
--   participant 를 전혀 참조하지 않음. auth 와 signatures 버킷만 공유.
-- =============================================================================
create table if not exists public.int_interviews (
    id uuid primary key default gen_random_uuid(),
    counselors uuid not null references auth.users (id) on delete cascade,
    name text not null,
    age text not null,
    gender text not null,
    mbti text not null,
    region text not null,
    hobby text not null default '',
    dream text not null default '',
    major_job text not null default '',
    schedule text not null default '',
    q1_why_qa text not null default '',
    q2_current_interest text not null default '',
    q3_one_hour_wish text not null default '',
    q4_what_tires text not null default '',
    q5_energy_focus text not null default '',
    q6_what_lacking text not null default '',
    q7_local_taste text not null default '',
    q8_ideal_day text not null default '',
    q9_needed_gathering text not null default '',
    q10_life_priority text not null default '',
    q11_one_wish text not null default '',
    q12_interview_thoughts text not null default '',
    -- 관심사 설문 (체크박스 중복 선택 → jsonb 배열로 저장)
    event_types jsonb not null default '[]'::jsonb,
    event_types_etc text not null default '',
    meeting_times jsonb not null default '[]'::jsonb,
    oneday_classes jsonb not null default '[]'::jsonb,
    oneday_classes_etc text not null default '',
    clubs jsonb not null default '[]'::jsonb,
    clubs_etc text not null default '',
    signatureurl text not null,
    created_at timestamptz not null default now()
);

-- 기존 테이블에 설문/확장 컬럼이 없으면 추가 (idempotent)
alter table public.int_interviews add column if not exists major_job text not null default '';
alter table public.int_interviews add column if not exists schedule text not null default '';
alter table public.int_interviews add column if not exists event_types jsonb not null default '[]'::jsonb;
alter table public.int_interviews add column if not exists event_types_etc text not null default '';
alter table public.int_interviews add column if not exists meeting_times jsonb not null default '[]'::jsonb;
alter table public.int_interviews add column if not exists oneday_classes jsonb not null default '[]'::jsonb;
alter table public.int_interviews add column if not exists oneday_classes_etc text not null default '';
alter table public.int_interviews add column if not exists clubs jsonb not null default '[]'::jsonb;
alter table public.int_interviews add column if not exists clubs_etc text not null default '';

create index if not exists idx_int_interviews_counselors on public.int_interviews (counselors);

alter table public.int_interviews enable row level security;

drop policy if exists "int_interviews_counselor_all" on public.int_interviews;
create policy "int_interviews_counselor_all" on public.int_interviews
  for all to authenticated
  using (auth.uid() = counselors)
  with check (auth.uid() = counselors);
