-- =============================================================================
-- Genie / Reframe — 코드(supabase.from / storage) 기준 스키마
-- =============================================================================
-- 설계 원칙 (Interview 와 Dashboard 완전 분리)
--   * Interview 화면(/interview)   → int_interviews 테이블만 사용 (단독)
--   * Dashboard 화면(/dashboard)   → participant + 검사 테이블들 (단독)
--   * 두 영역이 "공통"으로 쓰는 것은 딱 둘:
--       1) 인증        : auth.users  +  public.counselors
--       2) 서명 저장소 : storage 'signatures' 버킷
--   * 그 외에는 서로 참조하지 않으므로 각자 독립적으로 저장/조회/삭제됩니다.
--
-- 실제 셋업/복구용 실행 스크립트는 schema-separated.sql 을 사용하세요.
-- (RLS 정책까지 포함된 idempotent 버전)
--
-- Supabase 대시보드 → SQL Editor 에서 실행. 여러 번 실행해도 안전(idempotent).
-- =============================================================================

create extension if not exists "pgcrypto";


-- ---------------------------------------------------------------------------
-- [공통 1] 인증 — counselors (auth.users 와 1:1)
-- ---------------------------------------------------------------------------
create table if not exists public.counselors (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null unique references auth.users (id) on delete cascade,
    name text not null,
    email text not null,
    region text not null,
    photo_url text
);


-- ---------------------------------------------------------------------------
-- [DASHBOARD] 코칭 대상자 — participant (단독)
-- ---------------------------------------------------------------------------
create table if not exists public.participant (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    birth_date text not null,
    stress text not null,
    religion text not null,
    signatureurl text not null,
    counselors uuid not null references auth.users (id) on delete cascade,
    created_at timestamptz not null default now()
);

create index if not exists idx_participant_counselors on public.participant (counselors);


-- ---------------------------------------------------------------------------
-- [DASHBOARD] 검사 테이블들 — participant 에만 종속 (참가자 삭제 시 함께 삭제)
-- ---------------------------------------------------------------------------
create table if not exists public.core_emotion_tests (
    id bigint generated by default as identity primary key,
    participant_id uuid not null references public.participant (id) on delete cascade,
    answers jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.personality_tests (
    id bigint generated by default as identity primary key,
    participant_id uuid not null references public.participant (id) on delete cascade,
    answers jsonb not null default '{}'::jsonb
);

create table if not exists public.personality_tests2 (
    id bigint generated by default as identity primary key,
    participant_id uuid not null references public.participant (id) on delete cascade,
    answers jsonb not null default '{}'::jsonb
);

create table if not exists public.attachment_tests (
    id bigint generated by default as identity primary key,
    participant_id uuid not null references public.participant (id) on delete cascade,
    answers jsonb not null default '{}'::jsonb
);

create table if not exists public.lifegraphs (
    id bigint generated by default as identity primary key,
    participant_id uuid not null references public.participant (id) on delete cascade,
    image_url text not null
);

create table if not exists public.sixtypes (
    id bigint generated by default as identity primary key,
    participant_id uuid not null references public.participant (id) on delete cascade,
    image_url text not null
);

create table if not exists public.fourtypes (
    id bigint generated by default as identity primary key,
    participant_id uuid not null references public.participant (id) on delete cascade,
    image_url text not null
);


-- ---------------------------------------------------------------------------
-- [INTERVIEW] 지니 인터뷰 — int_interviews (단독)
--   participant 를 전혀 참조하지 않음. auth 와 signatures 버킷만 공유.
-- ---------------------------------------------------------------------------
create table if not exists public.int_interviews (
    id uuid primary key default gen_random_uuid(),
    counselors uuid not null references auth.users (id) on delete cascade,
    name text not null,
    age text not null,
    gender text not null,
    mbti text not null,
    region text not null,
    hobby text not null default '',
    dream text not null default '',
    q1_why_qa text not null default '',
    q2_current_interest text not null default '',
    q3_one_hour_wish text not null default '',
    q4_what_tires text not null default '',
    q5_energy_focus text not null default '',
    q6_what_lacking text not null default '',
    q7_local_taste text not null default '',
    q8_ideal_day text not null default '',
    q9_needed_gathering text not null default '',
    q10_life_priority text not null default '',
    q11_one_wish text not null default '',
    q12_interview_thoughts text not null default '',
    -- 관심사 설문 (체크박스 중복 선택 → jsonb 배열로 저장)
    event_types jsonb not null default '[]'::jsonb,
    event_types_etc text not null default '',
    meeting_times jsonb not null default '[]'::jsonb,
    oneday_classes jsonb not null default '[]'::jsonb,
    clubs jsonb not null default '[]'::jsonb,
    signatureurl text not null,
    created_at timestamptz not null default now()
);

create index if not exists idx_int_interviews_counselors on public.int_interviews (counselors);


-- ---------------------------------------------------------------------------
-- [기타] 위 두 영역과 무관한 공개/독립 테이블 (홈/소개 등에서 사용)
-- ---------------------------------------------------------------------------
create table if not exists public.contents (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    image_url text,
    is_featured boolean not null default false,
    is_recommended boolean not null default false,
    created_at timestamptz not null default now()
);

create table if not exists public.organization (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    website text,
    description text,
    logo_url text
);

create table if not exists public.responses (
    clientid text primary key,
    contact text not null,
    answers jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    firststamp boolean not null default false,
    secondstamp boolean not null default false,
    thirdstamp boolean not null default false,
    laststamp boolean not null default false
);


-- ---------------------------------------------------------------------------
-- Storage buckets
--   signatures            : [공통] 서명 이미지 (participant / int_interviews)
--   lifegraph/sixtypes/…  : [DASHBOARD] 검사 이미지
--   contents/organization-logos/counselor-photos : [기타]
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values
    ('signatures', 'signatures', true),
    ('lifegraph', 'lifegraph', true),
    ('sixtypes', 'sixtypes', true),
    ('fourtypes', 'fourtypes', true),
    ('contents', 'contents', true),
    ('organization-logos', 'organization-logos', true),
    ('counselor-photos', 'counselor-photos', true)
on conflict (id) do nothing;


-- ---------------------------------------------------------------------------
-- RLS
--   이 파일은 테이블 구조 참고용입니다.
--   RLS 정책(인증/소유자 기반)은 schema-separated.sql 에 정리되어 있으니
--   실제 적용은 그 파일을 실행하세요.
-- ---------------------------------------------------------------------------
