-- Reframe/Genie 앱 — 코드(supabase.from / storage) 기준 역추적 스키마
-- genie-site에서도 동일 Supabase 프로젝트를 쓸 때 참고용으로 복사됨.
-- Supabase 대시보드 → SQL Editor 에서 실행하세요.
-- RLS는 프로젝트 정책에 맞게 반드시 조정하세요 (아래 주석 참고).

-- extensions (uuid)
create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table if not exists public.counselors (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null unique references auth.users (id) on delete cascade,
    name text not null,
    email text not null,
    region text not null,
    photo_url text
);

create table if not exists public.participant (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    birth_date text not null,
    stress text not null,
    religion text not null,
    signatureurl text not null,
    counselors uuid not null references auth.users (id) on delete cascade,
    created_at timestamptz not null default now()
);

create index if not exists idx_participant_counselors on public.participant (counselors);

create table if not exists public.contents (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    image_url text,
    is_featured boolean not null default false,
    is_recommended boolean not null default false,
    created_at timestamptz not null default now()
);

create table if not exists public.organization (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    website text,
    description text,
    logo_url text
);

create table if not exists public.responses (
    clientid text primary key,
    contact text not null,
    answers jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    firststamp boolean not null default false,
    secondstamp boolean not null default false,
    thirdstamp boolean not null default false,
    laststamp boolean not null default false
);

create table if not exists public.core_emotion_tests (
    id bigint generated by default as identity primary key,
    participant_id uuid not null references public.participant (id) on delete cascade,
    answers jsonb not null default '{}'::jsonb,
    created_at timestamptz not null
);

create table if not exists public.personality_tests (
    id bigint generated by default as identity primary key,
    participant_id uuid not null references public.participant (id) on delete cascade,
    answers jsonb not null default '{}'::jsonb
);

create table if not exists public.personality_tests2 (
    id bigint generated by default as identity primary key,
    participant_id uuid not null references public.participant (id) on delete cascade,
    answers jsonb not null default '{}'::jsonb
);

create table if not exists public.attachment_tests (
    id bigint generated by default as identity primary key,
    participant_id uuid not null references public.participant (id) on delete cascade,
    answers jsonb not null default '{}'::jsonb
);

create table if not exists public.lifegraphs (
    id bigint generated by default as identity primary key,
    participant_id uuid not null references public.participant (id) on delete cascade,
    image_url text not null
);

create table if not exists public.sixtypes (
    id bigint generated by default as identity primary key,
    participant_id uuid not null references public.participant (id) on delete cascade,
    image_url text not null
);

create table if not exists public.fourtypes (
    id bigint generated by default as identity primary key,
    participant_id uuid not null references public.participant (id) on delete cascade,
    image_url text not null
);

-- ---------------------------------------------------------------------------
-- Storage buckets (파일 업로드용 — Dashboard Storage에서 public 설정도 가능)
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public)
values
    ('signatures', 'signatures', true),
    ('contents', 'contents', true),
    ('organization-logos', 'organization-logos', true),
    ('counselor-photos', 'counselor-photos', true),
    ('lifegraph', 'lifegraph', true),
    ('sixtypes', 'sixtypes', true),
    ('fourtypes', 'fourtypes', true)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- RLS (선택)
-- 새 테이블은 Supabase에서 RLS가 켜져 있으면 정책 없이는 막힐 수 있습니다.
-- 개발 중 빠르게 쓰려면 대시보드에서 테이블별로 RLS를 끄거나, 아래처럼 최소 정책을 추가하세요.
-- 운영 전에는 반드시 역할별로 좁혀야 합니다.
-- ---------------------------------------------------------------------------

-- 예시: 익명 사용자도 홈/소개에서 읽는 데이터
-- alter table public.contents enable row level security;
-- create policy "contents_select_anon" on public.contents for select to anon using (true);
-- create policy "contents_select_auth" on public.contents for select to authenticated using (true);

-- 예시: participant는 본인(user_id = counselors)만 CRUD
-- alter table public.participant enable row level security;
-- create policy "participant_counselor_all" on public.participant
--   for all to authenticated using (auth.uid() = counselors) with check (auth.uid() = counselors);

-- Storage: 업로드/조회 정책은 버킷별로 Dashboard → Storage → Policies 에서 설정하는 것이 가장 수월합니다.
