export const interviewLabels = {
    title: '인터뷰 대상자 관리',
    register: '인터뷰 등록',
    showList: '목록 보기',
    hideList: '목록 숨기기',
    search: '이름 검색',
    searchPlaceholder: '이름을 입력하세요...',
    colName: '이름',
    colAge: '나이',
    colGender: '성별',
    colMbti: 'MBTI',
    colRegion: '거주 지역',
    colActions: '관리',
    viewDetail: '상세 보기',
    edit: '수정',
    delete: '삭제',
    confirmDelete: '정말 삭제하시겠습니까?',
    deleteFailed: '삭제에 실패했습니다.',
    emptyResult: '검색 결과가 없습니다.',
} as const;
